export const PRESET_SCENARIOS = [
  {
    id: "ridge_escape",
    name: "Scenario 1: Ridge Escape",
    description:
      "Steep altitude rise on the left column makes the distance-minimizing route energy-heavy.",
    altitudeGrid: [
      [0, 0, 0, 0, 0, 0, 0, 0],
      [6, 1, 1, 1, 1, 1, 1, 1],
      [7, 1, 1, 1, 1, 1, 1, 1],
      [8, 1, 1, 1, 1, 1, 1, 1],
      [9, 1, 1, 1, 1, 1, 1, 1],
      [9, 1, 1, 1, 1, 1, 1, 1],
      [9, 1, 1, 1, 1, 1, 1, 1],
      [9, 1, 1, 1, 1, 1, 1, 1],
    ],
    start: [0, 0],
    end: [7, 7],
    environment: {
      windDirection: "E",
      windStrength: 1.2,
      altitudeFactor: 1.3,
      dynamicWindEnabled: false,
      windShiftStep: 6,
      windDirectionAfterShift: "W",
      windStrengthAfterShift: 2.2,
    },
    obstacles: [
      [2, 2],
      [3, 2],
      [4, 2],
      [5, 2],
      [5, 3],
      [5, 4],
    ],
  },
  {
    id: "mountain_turn",
    name: "Scenario 2: Mountain Turn",
    description:
      "A high-altitude lower corridor and northward tailwind reward moving upward first.",
    altitudeGrid: [
      [1, 1, 1, 1, 1, 1, 1, 1],
      [1, 2, 2, 2, 2, 2, 2, 1],
      [1, 2, 3, 3, 3, 3, 2, 1],
      [1, 2, 3, 4, 4, 3, 2, 1],
      [1, 2, 3, 4, 5, 3, 2, 1],
      [1, 2, 3, 4, 5, 4, 2, 1],
      [1, 2, 3, 4, 5, 5, 2, 1],
      [0, 7, 8, 9, 9, 9, 9, 1],
    ],
    start: [7, 0],
    end: [0, 7],
    environment: {
      windDirection: "N",
      windStrength: 1.8,
      altitudeFactor: 1.0,
      dynamicWindEnabled: true,
      windShiftStep: 5,
      windDirectionAfterShift: "E",
      windStrengthAfterShift: 2.5,
    },
    obstacles: [
      [6, 2],
      [6, 3],
      [6, 4],
      [5, 4],
      [4, 4],
      [3, 4],
    ],
  },
  {
    id: "valley_detour",
    name: "Scenario 3: Valley Detour",
    description:
      "Descending the right wall is short but costly; moving left early follows a low valley.",
    altitudeGrid: [
      [1, 1, 1, 1, 1, 1, 1, 0],
      [1, 1, 1, 1, 1, 1, 2, 7],
      [1, 1, 1, 1, 1, 2, 2, 8],
      [1, 1, 1, 1, 2, 2, 3, 9],
      [1, 1, 1, 2, 2, 3, 3, 9],
      [1, 1, 2, 2, 3, 3, 4, 9],
      [1, 2, 2, 3, 3, 4, 4, 9],
      [0, 1, 1, 1, 1, 1, 1, 9],
    ],
    start: [0, 7],
    end: [7, 0],
    environment: {
      windDirection: "W",
      windStrength: 1.5,
      altitudeFactor: 1.2,
      dynamicWindEnabled: true,
      windShiftStep: 6,
      windDirectionAfterShift: "S",
      windStrengthAfterShift: 2.3,
    },
    obstacles: [
      [1, 6],
      [2, 6],
      [3, 6],
      [4, 6],
      [5, 6],
      [6, 5],
    ],
  },
  {
    id: "headwind_valley",
    name: "Scenario 4: Headwind Valley",
    description:
      "Strong west wind blocks eastward movement. Direct path (7 steps) climbs HIGH mountains against headwind. Energy-aware routing chooses a 14-step detour through a deep valley where lower terrain offsets extra distance.",
    altitudeGrid: [
      [8, 9, 9, 9, 9, 9, 8, 8],
      [7, 8, 8, 8, 8, 8, 7, 7],
      [6, 7, 7, 7, 7, 7, 6, 6],
      [0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0],
      [2, 2, 2, 2, 2, 2, 2, 2],
      [4, 4, 4, 4, 4, 4, 4, 4],
      [6, 6, 6, 6, 6, 6, 6, 6],
    ],
    start: [0, 0],
    end: [0, 7],
    environment: {
      windDirection: "W",
      windStrength: 5.0,
      altitudeFactor: 3.0,
      downhillFactor: 0.35,
      dynamicWindEnabled: false,
      windShiftStep: 6,
      windDirectionAfterShift: "E",
      windStrengthAfterShift: 2.2,
    },
    obstacles: [],
  },
  {
    id: "storm_front_crossing",
    name: "Scenario 5: Storm Front Crossing",
    description:
      "Multiple wind phases with a short transition window simulate a storm front and trigger adaptive replanning.",
    altitudeGrid: [
      [0, 1, 1, 2, 2, 2, 1, 0],
      [0, 1, 2, 3, 3, 2, 1, 0],
      [0, 1, 2, 4, 5, 3, 1, 0],
      [0, 1, 2, 4, 5, 3, 1, 0],
      [0, 1, 2, 3, 3, 2, 1, 0],
      [0, 1, 1, 2, 2, 2, 1, 0],
      [0, 0, 1, 1, 1, 1, 0, 0],
      [0, 0, 0, 1, 1, 0, 0, 0],
    ],
    start: [7, 0],
    end: [0, 7],
    environment: {
      windDirection: "E",
      windStrength: 1.0,
      altitudeFactor: 1.1,
      dynamicWindEnabled: true,
      windShifts: [
        { step: 4, direction: "W", strength: 2.6, transitionSteps: 2, label: "Storm front" },
        { step: 9, direction: "S", strength: 1.8, label: "Post-front tail" },
      ],
      replanStrengthThreshold: 0.3,
      replanDirectionThreshold: Math.PI / 6,
    },
    obstacles: [
      [3, 2],
      [3, 3],
      [4, 3],
      [5, 4],
    ],
  },
  {
    id: "mountain_gust_corridor",
    name: "Scenario 6: Mountain Gust Corridor",
    description:
      "Localized gusts form a wind corridor along the ridge, forcing time-aware detours.",
    altitudeGrid: [
      [3, 3, 3, 4, 5, 6, 6, 6],
      [3, 2, 2, 3, 4, 5, 6, 6],
      [3, 2, 1, 2, 3, 4, 5, 6],
      [3, 2, 1, 2, 3, 4, 5, 6],
      [3, 2, 1, 2, 3, 4, 5, 6],
      [3, 2, 2, 3, 4, 5, 6, 6],
      [3, 3, 3, 4, 5, 6, 6, 6],
      [2, 2, 2, 3, 4, 5, 5, 5],
    ],
    start: [7, 0],
    end: [0, 7],
    environment: {
      windDirection: "N",
      windStrength: 1.4,
      altitudeFactor: 1.0,
      dynamicWindEnabled: true,
      windShifts: [
        { step: 6, direction: "NE", strength: 2.2, label: "Ridge gust" },
      ],
      gustRegions: [
        {
          startStep: 4,
          endStep: 10,
          rows: [2, 5],
          cols: [3, 6],
          direction: "E",
          strengthMultiplier: 1.8,
          label: "Corridor gust",
        },
      ],
      replanStrengthThreshold: 0.25,
      replanDirectionThreshold: Math.PI / 5,
    },
    obstacles: [
      [1, 2],
      [2, 2],
      [3, 2],
      [4, 2],
      [5, 2],
    ],
  },
  {
    id: "wind_reversal",
    name: "Scenario 7: Directional Reversal",
    description:
      "Wind reverses direction twice, testing adaptive replanning under sharp heading changes.",
    altitudeGrid: [
      [1, 1, 2, 3, 3, 2, 1, 1],
      [1, 2, 3, 4, 4, 3, 2, 1],
      [2, 3, 4, 5, 5, 4, 3, 2],
      [2, 3, 4, 4, 4, 4, 3, 2],
      [1, 2, 3, 3, 3, 3, 2, 1],
      [1, 1, 2, 2, 2, 2, 1, 1],
      [0, 1, 1, 1, 1, 1, 1, 0],
      [0, 0, 1, 1, 1, 1, 0, 0],
    ],
    start: [7, 1],
    end: [0, 6],
    environment: {
      windDirection: "E",
      windStrength: 1.6,
      altitudeFactor: 1.2,
      dynamicWindEnabled: true,
      windShifts: [
        { step: 3, direction: "W", strength: 2.4, label: "Reversal 1" },
        { step: 7, direction: "E", strength: 2.0, label: "Reversal 2" },
      ],
      replanStrengthThreshold: 0.3,
      replanDirectionThreshold: Math.PI / 3,
    },
    obstacles: [
      [3, 3],
      [4, 3],
      [5, 3],
    ],
  },
  {
    id: "valley_acceleration",
    name: "Scenario 8: Valley Wind Acceleration",
    description:
      "Wind accelerates through a valley (gradual strength increase), incentivizing time-aware routing.",
    altitudeGrid: [
      [4, 4, 4, 4, 4, 4, 4, 4],
      [3, 3, 3, 3, 3, 3, 3, 3],
      [2, 2, 2, 2, 2, 2, 2, 2],
      [1, 1, 1, 1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1, 1, 1, 1],
      [2, 2, 2, 2, 2, 2, 2, 2],
      [3, 3, 3, 3, 3, 3, 3, 3],
      [4, 4, 4, 4, 4, 4, 4, 4],
    ],
    start: [3, 0],
    end: [3, 7],
    environment: {
      windDirection: "E",
      windStrength: 0.8,
      altitudeFactor: 1.0,
      dynamicWindEnabled: true,
      windShifts: [
        { step: 4, direction: "E", strength: 2.8, transitionSteps: 3, label: "Valley acceleration" },
      ],
      replanStrengthThreshold: 0.2,
      replanDirectionThreshold: Math.PI / 6,
    },
    obstacles: [
      [2, 3],
      [2, 4],
      [5, 3],
      [5, 4],
    ],
  },
];

export function getScenarioById(id) {
  return PRESET_SCENARIOS.find((scenario) => scenario.id === id);
}

export function cloneGrid(grid) {
  return grid.map((row) => row.slice());
}
